### ISSUE TITLE
Reorganization of code

### ISSUE THREAD

**Issue by J08K** [Sandj04/InebriatingZenith#2]
A lot of reorganization of code is needed, as I have noticed some room for improvement for it to be more neat.

### TODOs

- [ ] **Views** Each page will have it's own module in the `/src/views/` directory. The `/src/__init__.py` will serve as holding global functions and connecting the different Flask Blueprints (views). This will make the code cleaner, but might add a small memory overhead due to multiple instances of database connection with the current design.
- [ ] **Configuration** Configuration is currently handled using a custom made module. This can cause problems. Switching to [Pydantic](https://docs.pydantic.dev/latest/) for the models and parsing is better for safety and reliability. It also helps with type safety and code readability.
- [ ] **Database** Currently, models are stored inside the `/src/db/schemas.py` module. Functionality for interacting with the database is also stored inside the `/src/db/` directory. This is a mess. I propose:
  - [ ] Moving the models inside a `/src/models` directory and separate weakly connected tables from each other into different modules.
  - [ ] Moving the functional modules from `/src/db` to the directory `/src/repository`.
